spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  cors:
    allowed-origins: http://localhost:4206,http://chess-advisor-frontend
